name: tests

on:
  push:
    branches:
    - feature/*
    - main

jobs:
  tests:
    uses: nzbgetcom/nzbget-extensions/.github/workflows/python-tests.yml@main
    with:
      python-versions: "3.3 3.4 3.5 3.6 3.7 3.8 3.9 3.10 3.11 3.12"
      supported-python-versions: "3.8 3.9 3.10 3.11 3.12"
      test-script: tests.py
